on:
  push:
    branches:
      - main   # change to master if that's your default

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch full history
          tags: true       # fetch tags as well

      - name: Mirror Repo1 to Repo2
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Add Repo2 remote (using the secret PAT)
          git remote add mirror https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Tyaran-dev/tayyran-app.git

          # Push all branches and tags, force overwrite
          git push --mirror --force mirror
